model_summary:
  _target_: pytorch_lightning.callbacks.RichModelSummary
  max_depth: 2

rich_progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar

model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "train/loss"
  mode: "min"
  save_top_k: -1
  save_last: true
  verbose: true
  dirpath: "checkpoints/"
  filename: "epoch={epoch:02d}-val_loss={val/loss:.4f}"
  every_n_epochs: 200
  auto_insert_metric_name: false
