# @package _global_

defaults:
  - _self_
  - data: spaghetti_author.yaml
  - model: ldm_default.yaml
  - callbacks: default.yaml
  - logger: multi_loggers.yaml
  - trainer: default.yaml
  - paths: default.yaml
  - hydra: default.yaml

  - experiment: phase2.yaml
  - debug: null

name: default
seed: 63

gpus: [0]
epochs: 5000
batch_size: 32

resume_from_checkpoint: null
