# @package _global_

defaults:
  - _self_
  - category: chair.yaml
  - model: phase1.yaml
  - callbacks: default.yaml
  - logger: tensorboard.yaml # multi_loggers.yaml
  - trainer: default.yaml
  - paths: default.yaml
  - hydra: default.yaml
  - debug: null

name: default
seed: 63

gpus: [0]
epochs: 5000
batch_size: 32

resume_from_checkpoint: null
