defaults:
- ldm_default.yaml

_target_: pvd.diffusion.phase1.ZaSALDM
network:
  _target_: pvd.diffusion.network.LatentLinearNetwork
  input_dim: 256
  embedding_dim: 512
  use_timestep_embedder: true
  timestep_embedder_dim: 128
  enc_num_layers: 6
  residual: true

validation_step: 1

dataset_kwargs:
  data_keys: ["za"]
