defaults:
  - ldm_lang_default.yaml

#_target_: pvd.diffusion.language_cond.LanguageGaussianSymSALDM
_target_: pvd.diffusion.language_cond.ShapeglotPhase1
network:
  _target_: pvd.diffusion.network.LatentConditionSelfAttentionNetwork
  input_dim: 16
  residual: true
  context_dim: 768
  context_embedding_dim: 1024
  embedding_dim: 512
  encoder_use_time: false
  encoder_type: pointwise
  decoder_type: transformer_encoder
  enc_num_layers: 2
  dec_num_layers: 6
  use_timestep_embedder: true
  timestep_embedder_dim: 128
  scale_eigenvectors: &scale_vectors false
  use_pos_encoding: false

classifier_free_guidance: false
conditioning_dropout_prob: 0.2

dataset_kwargs:
  data_keys: ["g_js_affine"]
  #lang_data_path: /home/juil/projects/3D_CRISPR/data/text2shape/T5embed2spaghetti_aug_ids.h5
  #lang_data_path: /home/juil/projects/3D_CRISPR/data/shapeglot/spaghetti_game_data.csv
