defaults:
- ldm_default.yaml

_target_: pvd.diffusion.phase1.GaussianSALDM
use_scaled_eigenvectors: false
network:
  _target_: pvd.diffusion.network.LatentSelfAttentionNetwork
  input_dim: 16
  embedding_dim: 512
  num_heads: 4
  use_timestep_embedder: true
  timestep_embedder_dim: 128
  enc_num_layers: 6
  residual: true
  scale_eigenvectors: ${model.use_scaled_eigenvectors} #*scale_vectors 
  encoder_type: transformer

validation_step: 1
eigen_value_clipping: false
eigen_value_clip_val: 1e-4

global_normalization: false

dataset_kwargs:
  data_keys: ["g_js_affine"]
  scale_eigenvectors: ${model.use_scaled_eigenvectors} #*scale_vectors
  global_normalization: ${model.global_normalization}
