defaults:
  - ldm_lang_default.yaml

#_target_: pvd.diffusion.language_cond.LanguageConditionIntrinsicLDM
_target_: pvd.diffusion.language_cond.ShapeglotPhase2
global_normalization: false
network:
  _target_: pvd.diffusion.network.LatentConditionSelfAttentionNetwork
  input_dim: 512
  residual: true
  context_dim: 784
  context_embedding_dim: 1024
  embedding_dim: 512
  encoder_use_time: false
  encoder_type: transformer
  decoder_type: transformer_encoder
  enc_num_layers: 6
  dec_num_layers: 6
  use_timestep_embedder: true
  timestep_embedder_dim: 128
  scale_eigenvectors: &scale_vectors false

classifier_free_guidance: false
conditioning_dropout_prob: 0.2

dataset_kwargs:
  data_keys: ["s_j_affine", "g_js_affine"]
  #lang_data_path: /home/juil/projects/3D_CRISPR/data/text2shape/T5embed2spaghetti_aug_ids.h5
  #lang_data_path: /home/juil/projects/3D_CRISPR/data/shapeglot/spaghetti_game_data.csv
