hydra:
  run:
    dir: ${save_dir}

defaults:
  - _self_

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: "gpu"
  devices: ${gpus}
  max_epochs: ${epochs}

work_dir: ${hydra:runtime.cwd}
save_dir: ${work_dir}/results/${name}/${now:%m%d_%H%M%S}

epochs: 200
batch_size: 16
gpus: [1]
seed: 63
name: default
debug: false

model:
  _target_: pvd.models.vae.PointNetVAE
  encoder: pointnet
  batch_size: ${batch_size}
  save_dir: ${save_dir}
  kl_weight: 1e-4

callbacks:
  model_summary:
    _target_: pytorch_lightning.callbacks.RichModelSummary
    max_depth: 1

  rich_progress_bar:
    _target_: pytorch_lightning.callbacks.RichProgressBar

  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "train/loss"
    mode: "min"
    save_top_k: 1
    save_last: true
    verbose: true
    dirpath: "checkpoints/"
    filename: "epoch={epoch:02d}-val_loss={val/loss:.4f}"
    auto_insert_metric_name: false

  lr_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "step"

logger:
  wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    project: "point-vae"
    name: ${name}
    save_dir: "."
    entity: "geometry"

  tensorboard:
    _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    save_dir: "tensorboard/"
    name: null
    version: ${name}
    log_graph: false
    default_hp_metric: true
    prefix: ""
